repos:
  - repo: local
    hooks:
      - id: lint
        name: lint files
        entry: make lint
        language: system
        types: [python]
        stages: [commit]
        pass_filenames: false