repos:
  - repo: local
    hooks:
      - id: lint
        name: lint files
        entry: make lint
        language: system
        types: [python]
        stages: [commit]
        pass_filenames: false

      - id: lock
        name: update lockfile
        entry: make lock
        language: script
        files: ^pyproject\.toml$
        stages: [ commit ]

      - id: requirements
        name: add requirements file
        entry: make requirements
        language: script
        files: ^pyproject\.toml$
        stages: [commit]

