repos:
  - repo: local
    hooks:
      - id: lint
        name: lint files
        entry: make lint
        language: system
        types: [python]
        stages: [commit]
        pass_filenames: false

      - id: lock
        name: update lockfile
        entry: .hooks/update_lock.sh
        language: script
        files: ^pyproject\.toml$
        stages: [commit]

      - id: requirements
        name: add requirements file
        entry: .hooks/requirements.sh
        language: script
        files: ^pyproject\.toml$
        stages: [commit]

